version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "elastic-project-management"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19d2d4iq3p1nh"
s3_prefix = "elastic-project-management"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
