AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Functions for the elastic project management application.
Globals:
    Function:
        CodeUri: code/built
Resources:
    ProdPubliclyAccessibleApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            Name: Prod Publicly Accessible Api
    ApiFunction:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ApiEvent:
                    Type: Api
                    Properties:
                        Path: /sign-up-new-user
                        Method: post
                        RestApiId:
                            Ref: ProdPubliclyAccessibleApi
            Runtime: nodejs14.x
            Handler: signUpNewUser.signUpNewUser
            FunctionName: SignUpNewUser
            Policies:
                - AmazonDynamoDBFullAccess
    ProdDynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            BillingMode: "PAY_PER_REQUEST"
            AttributeDefinitions:
                - AttributeName: "ItemId"
                  AttributeType: "S"
                - AttributeName: "BelongsTo"
                  AttributeType: "S"
                - AttributeName: "GSISortKey"
                  AttributeType: "S"
            KeySchema:
                - AttributeName: "ItemId"
                  KeyType: "HASH"
                - AttributeName: "BelongsTo"
                  KeyType: "RANGE"
            TableName: "primaryTableOne"
            GlobalSecondaryIndexes:
                - IndexName: "parentToChild"
                  KeySchema:
                      - AttributeName: "BelongsTo"
                        KeyType: "HASH"
                      - AttributeName: "ItemId"
                        KeyType: "RANGE"
                  Projection:
                      ProjectionType: "ALL"
                - IndexName: "parentWithSortedChild"
                  KeySchema:
                      - AttributeName: "BelongsTo"
                        KeyType: "HASH"
                      - AttributeName: "GSISortKey"
                        KeyType: "RANGE"
                  Projection:
                      ProjectionType: "ALL"
Outputs:
    SignUpNewUserApi:
        Description: "API Gateway endpoint URL for Prod"
        Value: !Sub "https://${ProdPubliclyAccessibleApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sign-up-new-user/"
