AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Functions for the elastic project management application.
Globals:
    Function:
        CodeUri: code/built
Resources:
    ProdPubliclyAccessibleApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            Name: Prod Publicly Accessible Api
    SignUpNewUserFunction:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ApiEvent:
                    Type: Api
                    Properties:
                        Path: /sign-up-new-user
                        Method: post
                        RestApiId:
                            Ref: ProdPubliclyAccessibleApi
            Runtime: nodejs14.x
            Handler: signUpNewUser.signUpNewUser
            FunctionName: SignUpNewUser
            Policies:
                - AmazonDynamoDBFullAccess
    ProdCognitoUserPool:
        Type: AWS::Cognito::UserPool
        Properties:
            AdminCreateUserConfig:
                AllowAdminCreateUserOnly: false
                InviteMessageTemplate:
                    EmailMessage: "Welcome to Elastic Project Management. Your username is {username} and temporary password is {####}. Visit elasticprojectmanagement.com/sign-in to sign in."
                    EmailSubject: "Elastic Project Management - Temporary Credentials"
            EmailConfiguration:
                SourceArn: arn:aws:ses:us-east-1:454305280052:identity/chasejarms@gmail.com
                EmailSendingAccount: DEVELOPER
                From: chasejarms@gmail.com
                ReplyToEmailAddress: chasejarms@gmail.com
            Policies:
                PasswordPolicy:
                    MinimumLength: 8
                    RequireLowercase: false
                    RequireNumbers: false
                    RequireSymbols: false
                    RequireUppercase: false
                    TemporaryPasswordValidityDays: 7
            AccountRecoverySetting:
                RecoveryMechanisms:
                    - Name: verified_email
                      Priority: 1
            UsernameConfiguration:
                CaseSensitive: false
            VerificationMessageTemplate:
                DefaultEmailOption: CONFIRM_WITH_LINK
                EmailMessageByLink: "Welcome to Elastic Project Management. Please click the following link to verify your email: {##Verify Email##}"
                EmailSubjectByLink: "Elastic Project Management - Verification Link"
    ProdAuthenticatedOnlyApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            Name: Prod Authenticated Only Api
            Auth:
                DefaultAuthorizer: ProdCognitoUserPool
                Authorizers:
                    ProdCognitoUserPool:
                        UserPoolArn:
                            Fn::GetAtt: [ProdCognitoUserPool, Arn]
    GetCompaniesForUserFunction:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ApiEvent:
                    Type: Api
                    Properties:
                        Path: /companies
                        Method: get
                        RestApiId:
                            Ref: ProdAuthenticatedOnlyApi
            Runtime: nodejs14.x
            Handler: getCompaniesForUser.getCompaniesForUser
            FunctionName: GetCompaniesForUser
            Policies:
                - AmazonDynamoDBFullAccess
    ProdDynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            BillingMode: "PAY_PER_REQUEST"
            AttributeDefinitions:
                - AttributeName: "ItemId"
                  AttributeType: "S"
                - AttributeName: "BelongsTo"
                  AttributeType: "S"
                - AttributeName: "GSISortKey"
                  AttributeType: "S"
            KeySchema:
                - AttributeName: "ItemId"
                  KeyType: "HASH"
                - AttributeName: "BelongsTo"
                  KeyType: "RANGE"
            TableName: "primaryTableOne"
            GlobalSecondaryIndexes:
                - IndexName: "parentToChild"
                  KeySchema:
                      - AttributeName: "BelongsTo"
                        KeyType: "HASH"
                      - AttributeName: "ItemId"
                        KeyType: "RANGE"
                  Projection:
                      ProjectionType: "ALL"
                - IndexName: "parentWithSortedChild"
                  KeySchema:
                      - AttributeName: "BelongsTo"
                        KeyType: "HASH"
                      - AttributeName: "GSISortKey"
                        KeyType: "RANGE"
                  Projection:
                      ProjectionType: "ALL"
Outputs:
    SignUpNewUserApi:
        Description: "API Gateway endpoint URL for Prod"
        Value: !Sub "https://${ProdPubliclyAccessibleApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sign-up-new-user/"
