AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Functions for the elastic project management application.
Resources:
    ProdPubliclyAccessibleApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            Name: Prod Publicly Accessible Api
            Cors: "'*'"
    ApiFunction: # Adds a GET api endpoint at "/" to the ApiGatewayApi via an Api event
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ApiEvent:
                    Type: Api
                    Properties:
                        Path: /sign-up-new-user
                        Method: post
                        RestApiId:
                            Ref: ProdPubliclyAccessibleApi
            Runtime: nodejs14.x
            Handler: app.signUpNewUserHandler
Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    SignUpNewUserApi:
        Description: "API Gateway endpoint URL for Prod"
        Value: !Sub "https://${ProdPubliclyAccessibleApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sign-up-new-user/"
