AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Functions for the elastic project management application.
Resources:
    LearningCenterStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./stacks/learning-center.yaml
    FrontendDistributionStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./stacks/frontend-distribution-stack.yaml
    PublicEndpointsStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./stacks/public-endpoints.yaml
    ProdCognitoUserPool:
        Type: AWS::Cognito::UserPool
        Properties:
            AdminCreateUserConfig:
                AllowAdminCreateUserOnly: false
                InviteMessageTemplate:
                    EmailMessage: "Welcome to Butter. Your username is {username} and temporary password is {####}. Visit butterpm.com/sign-in to sign in."
                    EmailSubject: "Butter Project Management - Temporary Credentials"
            EmailConfiguration:
                SourceArn: arn:aws:ses:us-east-1:454305280052:identity/info@butterpm.com
                EmailSendingAccount: DEVELOPER
                From: info@butterpm.com
                ReplyToEmailAddress: info@butterpm.com
            Policies:
                PasswordPolicy:
                    MinimumLength: 8
                    RequireLowercase: true
                    RequireNumbers: true
                    RequireSymbols: false
                    RequireUppercase: true
                    TemporaryPasswordValidityDays: 7
            AccountRecoverySetting:
                RecoveryMechanisms:
                    - Name: verified_email
                      Priority: 1
            UsernameConfiguration:
                CaseSensitive: false
            UsernameAttributes:
                - email
            VerificationMessageTemplate:
                DefaultEmailOption: CONFIRM_WITH_LINK
                EmailMessageByLink: "Welcome to Butter. Please click the following link to verify your email: {##Verify Email##}"
                EmailSubjectByLink: "Butter Project Management - Verification Link"
            AutoVerifiedAttributes:
                - email
            UserPoolName: ProdElasticProjectManagement
    ProdBackendAppClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
            ClientName: ElasticProjectManagementBackendClient
            GenerateSecret: false
            UserPoolId: !Ref ProdCognitoUserPool
    ProdUserPoolDomain:
        Type: AWS::Cognito::UserPoolDomain
        Properties:
            Domain: elastic-project-management
            UserPoolId: !Ref ProdCognitoUserPool
    ProdWebAppClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
            ClientName: ElasticProjectManagementWebClient
            GenerateSecret: false
            UserPoolId: !Ref ProdCognitoUserPool
            AccessTokenValidity: 43200
            IdTokenValidity: 43200
            RefreshTokenValidity: 2592000
            TokenValidityUnits:
                AccessToken: seconds
                IdToken: seconds
                RefreshToken: seconds
            ExplicitAuthFlows:
                - ALLOW_USER_PASSWORD_AUTH
                - ALLOW_REFRESH_TOKEN_AUTH
                - ALLOW_USER_SRP_AUTH
    PrivateEndpointsStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./stacks/authenticated-endpoints.yaml
            Parameters:
                ProdCognitoUserPoolArn: !GetAtt ProdCognitoUserPool.Arn
    CompanySourceFileBucket:
        Type: AWS::S3::Bucket
        Properties:
            AccessControl: "Private"
            BucketName: "elastic-project-management-company-source-files"
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - ServerSideEncryptionByDefault:
                          SSEAlgorithm: "AES256"
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true
    CompanyThumbnailFileBucket:
        Type: AWS::S3::Bucket
        Properties:
            AccessControl: "Private"
            BucketName: "elastic-project-management-company-thumbnail-files"
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - ServerSideEncryptionByDefault:
                          SSEAlgorithm: "AES256"
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true
    ProdDynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            BillingMode: "PAY_PER_REQUEST"
            AttributeDefinitions:
                - AttributeName: "itemId"
                  AttributeType: "S"
                - AttributeName: "belongsTo"
                  AttributeType: "S"
                - AttributeName: "directAccessTicketId"
                  AttributeType: "S"
            KeySchema:
                - AttributeName: "itemId"
                  KeyType: "HASH"
                - AttributeName: "belongsTo"
                  KeyType: "RANGE"
            TableName: "primaryTableOne"
            GlobalSecondaryIndexes:
                - IndexName: "parentToChild"
                  KeySchema:
                      - AttributeName: "belongsTo"
                        KeyType: "HASH"
                      - AttributeName: "itemId"
                        KeyType: "RANGE"
                  Projection:
                      ProjectionType: "ALL"
                - IndexName: "directAccessTicketId"
                  KeySchema:
                      - AttributeName: "directAccessTicketId"
                        KeyType: "HASH"
                  Projection:
                      ProjectionType: "ALL"
Outputs:
    ProdPubliclyAccessibleApi:
        Description: "Publicly accessible api for production."
        Value: !GetAtt PublicEndpointsStack.Outputs.ProdPubliclyAccessibleApi
    ProdAuthenticatedOnlyApi:
        Description: "Authenticated API Gateway Endpoint URL For Prod"
        Value: !GetAtt PrivateEndpointsStack.Outputs.ProdAuthenticatedOnlyApi
