AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Functions for the elastic project management application.
Resources:
    ProdPubliclyAccessibleApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            Name: Prod Publicly Accessible Api
    ApiFunction:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ApiEvent:
                    Type: Api
                    Properties:
                        Path: /sign-up-new-user
                        Method: post
                        RestApiId:
                            Ref: ProdPubliclyAccessibleApi
            Runtime: nodejs14.x
            Handler: app.signUpNewUserHandler
Outputs:
    SignUpNewUserApi:
        Description: "API Gateway endpoint URL for Prod"
        Value: !Sub "https://${ProdPubliclyAccessibleApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sign-up-new-user/"
