AWSTemplateFormatVersion: "2010-09-09"
Description: Learning Center S3 Bucket and Cloudfront Cluster
Transform: AWS::Serverless-2016-10-31
Resources:
    LearningCenterS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            AccessControl: "PublicRead"
            BucketName: "learning-center-files"
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - ServerSideEncryptionByDefault:
                          SSEAlgorithm: "AES256"
            PublicAccessBlockConfiguration:
                BlockPublicAcls: false
                BlockPublicPolicy: false
                IgnorePublicAcls: false
                RestrictPublicBuckets: false
    LearningCenterCloudFrontOriginAccessIdentity:
        Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
        Properties:
            CloudFrontOriginAccessIdentityConfig:
                Comment: "CloudFront OAI for Learning Center S3 Bucket"
    LearningCenterCloudFrontDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                DefaultCacheBehavior:
                    Compress: true
                    DefaultTTL: 60
                    ForwardedValues:
                        QueryString: true
                    MaxTTL: 60
                    TargetOriginId: !Ref LearningCenterS3Bucket
                    ViewerProtocolPolicy: "redirect-to-https"
                Enabled: true
                HttpVersion: "http2"
                IPV6Enabled: true
                Origins:
                    - DomainName: !GetAtt LearningCenterS3Bucket.DomainName
                      Id: !Ref LearningCenterS3Bucket
                      S3OriginConfig:
                          OriginAccessIdentity:
                              !Join [
                                  "",
                                  [
                                      "origin-access-identity/cloudfront/",
                                      !Ref LearningCenterCloudFrontOriginAccessIdentity,
                                  ],
                              ]
                PriceClass: "PriceClass_All"
